language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- /^v\d+\.\d+\.\d+$/
env:
  global:
    secure: NFFkeQGpEWIwfcJYra5PMoJS5+zTdc2iCC20wLaJx7Md561RJ5naaOMRTb0oBBXvbCg+4Vx+j8lVYx0d3Z/xecYgxivcVwH9KOXNYQmRUwL3wkS7Ihd2093OqlFZhh6hICFed4CpMpZyKKrTgL21sbS9Ujh6qr+2NNqJtfC/AAMVdqABxBSmhfGupvRupF255VYzl/qvplSx4Uq97JpSzbFKLCh8+nT6u89WOYl0XAMKS/x3NlvC2SEwyslPnZe+X5U31EfhknliC1oppJIkchaPbfDI9gZDuA2cJ5oABZ2NX9/etEmZPIBOVYXsurmxiHpU3wTDxoZuawGYBTq+fKllJSwAXfyIHns2Zh0Ugnk9uQeVgCB9lkji90Q8eP3Z7xdO+aC2DsimBL40rvq7wiDdo0xySghN0NV3MD6m3EqiyP8zA4KgBR+BSzEl6fCSlKyHl6Nd8mQX/4bV9QFGH3iEfbLPJ6pAAYR1FYrMPXptn5uysyVx1DOHu3lpSsudHJBLue3L/e5WzCCm1H/Ovy1JzDDrc8lN7C14xhEQNz+PjNCgWl7avFa09uBaTqF6fpfOvyshViCuEZmMvC0wrJgmANO8yvd+B4jpzS34gQNGMZ9e/ck6OG5eo7OuwPaOOoOTNTTEhys0D0s93UCsJ8R6+uM30AnEf8y4Q1R1uLQ=
