language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- /^v\d+\.\d+\.\d+$/
env:
  global:
    secure: GBLXXrwsqfYAWThCx73NiTJKuYhW2SB3LC/c/FkxTjP1DUrUaH/Arfct3AqFiqDjEP5TEW6XKWtji7s7CDVge091tWlQz8Ebmi+noEh5qe2Jkqklvcjae9ka0u1166o7NF0g4kWGbhDR2ADIynLaWDrgYZe0LJPCRU+Tlx34uXJkngxs/VSNmiAB7rAGVftuW1rB5HWgd7WNQeUD+b/SopeSNwZQwKBuA9t67MCIlOBL5zwFv/PkaKfJ8LwxBYgRf8W78dMpifqQ2j1RWgvrOUSk0fVPx+Ie2Urjz2fwkj7bbmICz0MzVU4Tz0uEoSF9bmabdUE0cBgAuINnbKzM0Dx1yP6M6AfFFvHsGwS0egaQYYCEbDJQ+LpPTG+fAi7vR2zqDL4KN7z3qnpHKhr0x8n4mFRuz1FW+sCXcc2oAuZI6a8rl2VfmBRnsvti6cQT/icCwfs7F5GUjX3rypSNlYri1F4LdLnCyLO+Wz0geo532MCs5kcUfNl70WeQAYa6eCMsjPEOkPXYGAAM8TWO506U28cJCjJOKYdOAsbE4Y39tDSvHFvm+JQQVD53iNXfan15vQAOYyRnTPEDil0L4ZjM6VGdC7tHDeCjQ1ARYEAp2G4VVzmLc9872D8U8AzbOyqODKdegwQuak5NUF8gIxVdjpAXZuR7l7xk8bfHaj8=
